#!/usr/bin/env node
// Regenerates the index table at the top of docs/DECISIONS.md from the file's own `## D<n> — …` headings,
// between the index:start / index:end markers.
//
// Generated rather than hand-written because a hand-maintained index of a growing file is a stale index.
// Nothing here interprets a decision; it only lists them.
//
// The heading order in the file is deliberately NOT the index order: entries D1–D28 run oldest-first and
// everything after runs newest-first, because the newest decision is the one a session usually wants. The
// index sorts numerically so an id can be found regardless.
//
// Usage: node devtools/dev.mjs decisions-index [--check]
//   --check  exit 1 if the index is out of date (for a gate), writing nothing.
//
// The anchor slugs are the part that breaks silently — a wrong slug is a link that 404s inside the file —
// which is what its tests pin.

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = fileURLToPath(import.meta.url)
const repoDefault = path.resolve(path.dirname(here), '..', '..')

export const START = '<!-- index:start — generated by `node devtools/dev.mjs decisions-index`; do not hand-edit -->'
export const END = '<!-- index:end -->'

/** An HTML comment is not heading TEXT: GitHub drops it before slugging, and a table cell must not carry it. */
const withoutComments = (s) => s.replace(/<!--[\s\S]*?-->/g, '')

/** How an entry declares itself a stub: the keyword capitalised, then the entry that now holds its content. */
const STUB = /\b(?:SUPERSEDED by|REVERSED by|MERGED INTO) (D\d+)/

/** The same declaration as a BANNER — a blockquote opening the body with the keyword in bold. */
const STUB_BANNER = /^>\s*\*\*(?:SUPERSEDED by|REVERSED by|MERGED INTO) (D\d+)/

/** `## D42 — Title (2026-08-05)` → `{ id, n, title, date, line, text, comments }`. Anything else is not a
 * decision heading. `text` is the heading as GitHub slugs it: comments removed, the space before one kept.
 * `comments` are the heading's own, whole — a gate's escape (`drift-ok`) the index row must carry too. */
export function decisionRows(lines) {
  const rows = []
  lines.forEach((l, i) => {
    if (!l.startsWith('## D')) return
    let j = 4
    while (j < l.length && l[j] >= '0' && l[j] <= '9') j++
    const id = l.slice(3, j)
    if (id.length < 2) return
    const text = withoutComments(l.slice(3).trimEnd())
    let rest = withoutComments(l.slice(j)).trim()
    while (rest.startsWith('—') || rest.startsWith('–') || rest.startsWith('-')) rest = rest.slice(1).trim()
    let date = null
    if (rest.endsWith(')')) {
      const open = rest.lastIndexOf('(')
      const inner = rest.slice(open + 1, -1)
      if (open > 0 && inner.length === 10 && inner[4] === '-' && inner[7] === '-') {
        date = inner
        rest = rest.slice(0, open).trim()
      }
    }
    const comments = (l.match(/<!--[\s\S]*?-->/g) ?? []).join(' ')
    rows.push({ id, n: Number(id.slice(1)), title: rest, date, line: i + 1, text, comments })
  })

  // Which entries are SUPERSEDED REDIRECTS rather than live decisions.
  //
  // `D<n>` numbers are permanent identifiers — 510 references across the repository point at them and
  // nothing gates those — so an overturned decision keeps its number and becomes a stub naming its
  // successor. Which numbers are stubs is the navigational fact a current-state record most needs to
  // surface, and it is DERIVED here because the preamble used to hand-list this file's amendment roster and
  // had drifted to naming three of the fifteen that carried one (found 2026-08-14, the audit that produced
  // the rebuild). A file whose own preamble says "use the index" cannot afford an index that under-reports.
  //
  // A stub declares itself in its HEADING (`## D80 — MERGED INTO D77`, or the parenthesised
  // `## D9 — Scope: … (SUPERSEDED by D14)`) or in a BANNER — a blockquote that is the first body line
  // (`> **REVERSED by D137.** …`). A banner further down, or one opening "Public half REVERSED by", leaves
  // the entry live: only a declaration where a reader lands counts.
  // The ways a number stops being a live decision, and all need surfacing:
  //   SUPERSEDED by / REVERSED by D<n> — a later decision overturned it;
  //   MERGED INTO D<n>                 — it was an application of another entry, and now lives there;
  //   RECLASSIFIED                     — it was never a decision at all, and its content moved to the record
  //                                      that fits (the task archive for a work log, pitfalls for a trap).
  for (const row of rows) {
    const heading = row.text
    let body = row.line
    while (body < lines.length && lines[body].trim() === '') body++
    const banner = body < lines.length && !lines[body].startsWith('## ') ? lines[body] : ''
    const m = STUB.exec(heading) ?? STUB_BANNER.exec(banner)
    row.supersededBy = m ? m[1] : null
    row.reclassified = /\bRECLASSIFIED\b/.test(heading)
  }
  return rows
}

/**
 * The GitHub heading anchor for a row — the one output nobody notices being wrong, because a broken
 * in-document link is not an error anywhere. github-slugger's rule over the WHOLE heading text (id, title
 * and date): lowercased, punctuation dropped (letters, marks, digits, `_` and `-` survive), each space to a
 * hyphen, nothing trimmed.
 */
export const slug = (r) => (r.text ?? `${r.id} — ${r.title}${r.date ? ` (${r.date})` : ''}`)
  .toLowerCase().replace(/[^\p{L}\p{M}\p{N}\p{Pc} -]/gu, '').replace(/ /g, '-')

/** Titles are one table cell; a long one is elided rather than wrapping the table into unreadability. */
export const short = (t) => (t.length <= 100 ? t : `${t.slice(0, 97).trimEnd()}…`)

/**
 * The generated block, marker to marker. Sorted NUMERICALLY.
 *
 * <p>Carries the SUPERSEDED-redirect roster as well as the table, so the one navigational claim this file
 * makes about itself is derived from the headings rather than remembered — the preamble's hand-maintained
 * version had drifted to naming three of fifteen before the 2026-08-14 rebuild.</p>
 */
export function indexBlock(rows, eol = '\n') {
  const sorted = rows.slice().sort((a, b) => a.n - b.n)
  const table = [
    '| # | Date | Decision |',
    '|---|---|---|',
    ...sorted.map((r) => `| [${r.id}](#${slug(r)}) | ${r.date ?? '—'} | ${short(r.title)}${r.comments ? ` ${r.comments}` : ''} |`),
  ].join(eol)

  const stubs = sorted.filter((r) => r.supersededBy || r.reclassified)
  const live = sorted.length - stubs.length
  const roster = stubs.length === 0
    ? `_All ${sorted.length} entries are live decisions._`
    : `**${live} live decisions.** The rest are stubs — \`D<n>\` is a permanent identifier, so a number is `
      + `never reused or renumbered (${stubs.length}): `
      + `${stubs.map((r) => `[${r.id}](#${slug(r)})${r.supersededBy ? ` → ${r.supersededBy}` : ' (reclassified)'}`).join(' · ')}`

  return [START, '', table, '', roster, '', END].join(eol)
}

/**
 * The document with its index regenerated. `{ rows, updated }`, or `{ rows, updated: null }` when there is
 * nowhere to put it — refusing to write is the right answer for both empty cases, since an index that
 * silently becomes empty is worse than one that is out of date.
 */
export function withIndex(text) {
  const eol = text.includes('\r\n') ? '\r\n' : '\n'
  const rows = decisionRows(text.split(/\r?\n/))
  if (rows.length === 0) return { rows, updated: null, reason: 'no-headings' }

  const block = indexBlock(rows, eol)
  const s = text.indexOf(START)
  const e = text.indexOf(END)
  if (s >= 0 && e > s) return { rows, updated: text.slice(0, s) + block + text.slice(e + END.length) }

  // First run: insert immediately before the first decision heading.
  const anchor = text.indexOf(`${eol}## D`)
  if (anchor < 0) return { rows, updated: null, reason: 'no-anchor' }
  return { rows, updated: `${text.slice(0, anchor)}${eol}${block}${text.slice(anchor)}` }
}

/** The command. `read`/`write` are seams so a test never touches the real docs/DECISIONS.md. */
export function decisionsIndex({
  file = path.join(repoDefault, 'docs', 'DECISIONS.md'),
  check = false,
  log = console.log,
  error = console.error,
  read = null,
  write = null,
} = {}) {
  const text = (read ?? (() => fs.readFileSync(file, 'utf8')))()
  const { rows, updated, reason } = withIndex(text)

  if (reason === 'no-headings') {
    error('decisions-index: no `## D<n>` headings found — refusing to write an empty index')
    return 1
  }
  if (reason === 'no-anchor') {
    error('decisions-index: could not find an insertion point')
    return 1
  }

  if (check) {
    if (updated !== text) {
      error(`decisions-index: OUT OF DATE (${rows.length} entries) — run \`node devtools/dev.mjs decisions-index\``)
      return 1
    }
    log(`decisions-index: up to date (${rows.length} entries) ✓`)
    return 0
  }
  if (updated === text) {
    log(`decisions-index: already current (${rows.length} entries)`)
    return 0
  }
  ;(write ?? ((t) => fs.writeFileSync(file, t, 'utf8')))(updated)
  log(`decisions-index: wrote ${rows.length} entries into docs/DECISIONS.md`)
  return 0
}

// CLI entry point — a thin wrapper, so importing this module for a test reads and writes nothing.
// `import.meta.main` where the runtime has it (Node >= 24.2); the argv fallback compares resolved paths,
// and a wrong comparison makes this do NOTHING and exit 0. Pinned by cli-entry.test.mjs.
if (import.meta.main ?? (process.argv[1] && path.resolve(process.argv[1]) === here)) {
  process.exitCode = decisionsIndex({ check: process.argv.includes('--check') })
}
