#!/usr/bin/env node
// Regenerates the index table at the top of docs/DECISIONS.md from the file's own `## D<n> — …` headings,
// between the index:start / index:end markers.
//
// Why this is generated rather than hand-written: DECISIONS.md is ~1300 lines and 44 entries and still
// growing, and a hand-maintained index of a growing file is a stale index — the exact defect class the
// 2026-08-05 review spent its time on. Nothing here interprets a decision; it only lists them.
//
// The heading order in the file is deliberately NOT the index order: entries D1–D28 run oldest-first and
// everything after runs newest-first, because the newest decision is the one a session usually wants. The
// index sorts numerically so an id can be found regardless.
//
// Usage: node devtools/dev.mjs decisions-index [--check]
//   --check  exit 1 if the index is out of date (for a gate), writing nothing.

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..')
const file = path.join(repo, 'docs', 'DECISIONS.md')
const START = '<!-- index:start — generated by `node devtools/dev.mjs decisions-index`; do not hand-edit -->'
const END = '<!-- index:end -->'

const text = fs.readFileSync(file, 'utf8')
const eol = text.includes('\r\n') ? '\r\n' : '\n'
const lines = text.split(/\r?\n/)

const rows = []
lines.forEach((l, i) => {
  if (!l.startsWith('## D')) return
  let j = 4
  while (j < l.length && l[j] >= '0' && l[j] <= '9') j++
  const id = l.slice(3, j)
  if (id.length < 2) return
  let rest = l.slice(j).trim()
  while (rest.startsWith('—') || rest.startsWith('–') || rest.startsWith('-')) rest = rest.slice(1).trim()
  let date = null
  if (rest.endsWith(')')) {
    const open = rest.lastIndexOf('(')
    const inner = rest.slice(open + 1, -1)
    if (open > 0 && inner.length === 10 && inner[4] === '-' && inner[7] === '-') {
      date = inner
      rest = rest.slice(0, open).trim()
    }
  }
  rows.push({ id, n: Number(id.slice(1)), title: rest, date, line: i + 1 })
})

if (rows.length === 0) {
  console.error('decisions-index: no `## D<n>` headings found — refusing to write an empty index')
  process.exitCode = 1
} else {
  const slug = (r) => `${r.id} — ${r.title}${r.date ? ` (${r.date})` : ''}`
    .toLowerCase().replace(/[^\p{L}\p{N}\s-]/gu, '').trim().replace(/\s+/g, '-')
  const short = (t) => (t.length <= 100 ? t : `${t.slice(0, 97).trimEnd()}…`)

  const table = [
    '| # | Date | Decision |',
    '|---|---|---|',
    ...rows.slice().sort((a, b) => a.n - b.n).map((r) => `| [${r.id}](#${slug(r)}) | ${r.date ?? '—'} | ${short(r.title)} |`),
  ].join(eol)

  const block = [START, '', table, '', END].join(eol)

  const s = text.indexOf(START)
  const e = text.indexOf(END)
  let updated
  if (s >= 0 && e > s) {
    updated = text.slice(0, s) + block + text.slice(e + END.length)
  } else {
    // First run: insert immediately before the first decision heading.
    const anchor = text.indexOf(`${eol}## D`)
    if (anchor < 0) { console.error('decisions-index: could not find an insertion point'); process.exit(1) }
    updated = `${text.slice(0, anchor)}${eol}${block}${text.slice(anchor)}`
  }

  if (process.argv.includes('--check')) {
    if (updated !== text) {
      console.error(`decisions-index: OUT OF DATE (${rows.length} entries) — run \`node devtools/dev.mjs decisions-index\``)
      process.exitCode = 1
    } else {
      console.log(`decisions-index: up to date (${rows.length} entries) ✓`)
    }
  } else if (updated === text) {
    console.log(`decisions-index: already current (${rows.length} entries)`)
  } else {
    fs.writeFileSync(file, updated, 'utf8')
    console.log(`decisions-index: wrote ${rows.length} entries into docs/DECISIONS.md`)
  }
}
