// check-decisions — the decision-entry length gate. See devtools/scripts/check-decisions.mjs.
//
// A guard whose failure mode is a false PASS cannot be validated by running it, so the negative cases here
// matter as much as the positive ones — and the RATCHET has two negative directions: an entry over its
// budget must fail, AND an allowance looser than the entry needs must fail. The second is what keeps the
// debt shrinking; without it the registry is a permanent permission slip.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, it } from 'node:test';

import {
  MAX_ENTRY, RECORD, checkDecisions, entriesIn, overLimitEntries,
} from '../check-decisions.mjs';
import { makeTree, recorder, removeTree } from './_fixtures.mjs';

const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..', '..');

/** A decision entry with `n` non-blank body lines, paragraph-broken so blanks are exercised. */
const entry = (id, n, title = 'a decision') =>
  [`## ${id} — ${title} (2026-08-28)`, '',
    ...Array.from({ length: n }, (_, i) => (i % 3 === 2 ? `body ${i}\n` : `body ${i}`)),
  ].join('\n');

const record = (...entries) => ['# Decisions', '', '| index | table |', '|---|---|', '',
  ...entries].join('\n') + '\n';

function run(text, cfg) {
  const dir = makeTree({ [RECORD]: text });
  const log = recorder();
  try {
    return { code: checkDecisions(dir, cfg, log), out: log.text() };
  } finally {
    removeTree(dir);
  }
}

describe('check-decisions — finding the entries', () => {
  it('counts NON-BLANK body lines and excludes the heading itself', () => {
    // Blank lines are paragraph separators, not prose. Counting them would measure formatting, and an
    // entry could be "paid down" by unwrapping its paragraphs without deleting a word.
    const e = entriesIn(record(entry('D1', 4)));
    assert.equal(e.length, 1);
    assert.equal(e[0].length, 4);
  });

  it('ignores everything above the first entry, so the generated index is not an entry', () => {
    // The index table at the top of the record is regenerated by `dev.mjs decisions-index`; counting it
    // would make the gate fail for a reason no author controls.
    assert.deepEqual(entriesIn(record(entry('D1', 2))).map((x) => x.id), ['D1']);
  });

  it('the last entry runs to end of file', () => {
    const e = entriesIn(record(entry('D1', 2), entry('D2', 7)));
    assert.deepEqual(e.map((x) => [x.id, x.length]), [['D1', 2], ['D2', 7]]);
  });

  it('reports the heading line number, so a failure points at the entry', () => {
    const e = entriesIn(record(entry('D1', 2), entry('D2', 2)));
    assert.equal(e[0].line, 6);
    assert.ok(e[1].line > e[0].line);
  });

  it('a two-digit id is not confused with a one-digit id', () => {
    assert.deepEqual(entriesIn(record(entry('D9', 1), entry('D95', 1))).map((x) => x.id), ['D9', 'D95']);
  });

  it('overLimitEntries returns only entries past the limit, worst first', () => {
    const over = overLimitEntries(record(entry('D1', MAX_ENTRY + 1), entry('D2', 2), entry('D3', MAX_ENTRY + 9)));
    assert.deepEqual(over.map((x) => x.id), ['D3', 'D1']);
  });

  it('an entry exactly AT the limit is not over it', () => {
    assert.deepEqual(overLimitEntries(record(entry('D1', MAX_ENTRY))), []);
  });
});

describe('check-decisions — the ratchet', () => {
  it('passes a record whose entries are all within the limit', () => {
    const { code, out } = run(record(entry('D1', 5), entry('D2', 9)), {});
    assert.equal(code, 0);
    assert.match(out, /✓/);
  });

  it('FAILS an over-limit entry that carries no allowance', () => {
    const { code, out } = run(record(entry('D1', MAX_ENTRY + 6)), {});
    assert.equal(code, 1);
    assert.match(out, /D1/);
    assert.match(out, new RegExp(String(MAX_ENTRY + 6)));
  });

  it('passes an over-limit entry whose allowance matches it exactly', () => {
    const { code } = run(record(entry('D1', MAX_ENTRY + 6)), { decisionLengthAllowances: { D1: MAX_ENTRY + 6 } });
    assert.equal(code, 0);
  });

  it('FAILS when an entry grows past its own allowance', () => {
    const { code, out } = run(record(entry('D1', MAX_ENTRY + 7)), { decisionLengthAllowances: { D1: MAX_ENTRY + 6 } });
    assert.equal(code, 1);
    assert.match(out, /D1/);
  });

  it('FAILS an allowance that is LOOSER than the entry needs — the numbers only come down', () => {
    // Without this the registry becomes a permission slip: an entry paid down to 20 keeps a budget of 60,
    // and the next regression back up to 60 passes unnoticed.
    const { code, out } = run(record(entry('D1', MAX_ENTRY + 2)), { decisionLengthAllowances: { D1: MAX_ENTRY + 9 } });
    assert.equal(code, 1);
    assert.match(out, /looser|lower/i);
  });

  it('FAILS an allowance on an entry that is now within the limit — delete it', () => {
    const { code, out } = run(record(entry('D1', 5)), { decisionLengthAllowances: { D1: MAX_ENTRY + 4 } });
    assert.equal(code, 1);
    assert.match(out, /looser|lower/i);
  });

  it('FAILS an allowance naming an entry that does not exist', () => {
    const { code, out } = run(record(entry('D1', 5)), { decisionLengthAllowances: { D404: 60 } });
    assert.equal(code, 1);
    assert.match(out, /D404/);
  });

  it('reports the remaining debt on success, so the ledger is visible without opening the config', () => {
    const { out } = run(record(entry('D1', MAX_ENTRY + 10)), { decisionLengthAllowances: { D1: MAX_ENTRY + 10 } });
    assert.match(out, /1 entr/);
  });
});

describe('check-decisions — failing closed', () => {
  it('FAILS when the record is missing rather than reporting a clean tree', () => {
    // The shape that let `check-sensitive` skip every renamed file: a guard that finds nothing to scan must
    // indict the listing, never announce success.
    const dir = makeTree({ 'docs/other.md': '# not the record\n' });
    const log = recorder();
    try {
      assert.equal(checkDecisions(dir, {}, log), 1);
      assert.match(log.text(), /✗/);
    } finally {
      removeTree(dir);
    }
  });

  it('FAILS a record that declares no entries at all', () => {
    const { code, out } = run('# Decisions\n\nno entries here\n', {});
    assert.equal(code, 1);
    assert.match(out, /✗/);
  });
});

describe('check-decisions — against the real record', () => {
  it('the shipped record parses into a contiguous D1..Dn with no gaps', () => {
    // Pins the parser against the real tree, not a fixture. `check-comments`' first counter returned the
    // right total from two cancelling errors, and only comparing the parsed NAMES caught it.
    const entries = entriesIn(fs.readFileSync(path.join(repo, RECORD), 'utf8'));
    assert.ok(entries.length >= 95, `expected the real record to parse, got ${entries.length}`);
    const nums = entries.map((e) => Number(e.id.slice(1)));
    assert.deepEqual(nums, Array.from({ length: nums.length }, (_, i) => i + 1));
  });
});
